### PR TITLE
GIB💎WORK Bounty - Pull Request Made To anchor

### PR DESCRIPTION
**Pull request by SoSoDolo**
🤖 This pull request was created by https://app.gib.work/r/Ql3a0gKk/anchor 
 ⚡️ Payment for bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by SoSoDolo** [comment]
@acheroncrypto any reason this was marked as duplicate but there hasn't been an accepted PR? Just looking for some feedback

**Comment by acheroncrypto** [comment]
Hey, this looked like a spam to me since it's bringing out some random commits that was made in the past with autogenerated PR title and description:

image

There was also another PR(https://github.com/coral-xyz/anchor/pull/2752) with the same PR title.

**Comment by SoSoDolo** [comment]
@acheroncrypto Oh yeah not sure about the extra commits but the title is auto generated from GibWork so anybody that tries to claim will have this title I believe. Or is that not an actual bounty for this repo?

**Comment by acheroncrypto** [comment]
> Or is that not an actual bounty for this repo?

There could be but I'm not the person who created it.

Also, we can reopen the PR if you fix the extra commits and add the correct types. The types in https://github.com/coral-xyz/anchor/pull/2752 is not correct either, the Rust types are here: https://github.com/coral-xyz/anchor/blob/de9901b5fd739d80d5d881c8892b71083b24c987/lang/syn/src/idl/types.rs#L88-L122

**Pull request closed without merging**
