### PR TITLE
Update Cargo.toml

### PR DESCRIPTION
**Pull request by bryanc12**
Fix compilation error on Windows 10.

### CODE REVIEW

**Comment by acheroncrypto** [comment]
This is not necessary because `solana-client` allows any version above `tokio 1.14.1` now(https://github.com/solana-labs/solana/pull/33058). You can verify that adding `anchor-client` will use the latest `tokio` version which is `1.32.0` as of right now.

```sh
cargo new latest-tokio
cargo add anchor-client
cargo build
cargo tree -i tokio --depth 0
```

will output

```sh
tokio v1.32.0
```

**Comment by bryanc12** [comment]
> This is not necessary because `solana-client` allows any version above `tokio 1.14.1` now(https://github.com/solana-labs/solana/pull/33058). You can verify that adding `anchor-client` will use the latest `tokio` version which is `1.32.0` as of right now.
> 
> 
> 
> ```sh
> 
> cargo new latest-tokio
> 
> cargo add anchor-client
> 
> cargo build
> 
> cargo tree -i tokio --depth 0
> 
> ```
> 
> 
> 
> will output
> 
> 
> 
> ```sh
> 
> tokio v1.32.0
> 
> ```
> 
> 

But when it's not specifying a version, it's causing build failure on Windows 10, platform which I tried to build on.

**Comment by acheroncrypto** [comment]
Could you share the output after running the exact same commands I've shared?

**Comment by bryanc12** [comment]
> Could you share the output after running the exact same commands I've shared?

image
Get this error when running on Git Bash, Powershell and Command Prompt.

**Comment by acheroncrypto** [comment]
Well that's not running the commands that I've shared above. As the output suggests, you are trying to compile `anchor-cli 0.28.0` which uses `--locked` argument when installing via `avm`, hence the outdated `tokio` version. You can install without the `--locked` argument to get the updated dependencies:

```sh
cargo install --git https://github.com/coral-xyz/anchor --tag v0.28.0 anchor-cli
```

**Comment by bryanc12** [comment]
> Well that's not running the commands that I've shared above. As the output suggests, you are trying to compile `anchor-cli 0.28.0` which uses `--locked` argument when installing via `avm`, hence the outdated `tokio` version. You can install without the `--locked` argument to get the updated dependencies:
> 
> ```shell
> cargo install --git https://github.com/coral-xyz/anchor --tag v0.28.0 anchor-cli
> ```

Okay, thanx alot!

**Pull request closed without merging**
