### PR TITLE
Add `destroy` account constraint

### PR DESCRIPTION
**Pull request by Henry-E**
Add a `destroy=[target]` account constraint which
- reallocs the account space to 8 bytes
- sends the rest of the lamports to `[target]`
- assigns the `CLOSED_ACCOUNT_DISCRIMINATOR
This will prevent the account from ever being opened against, effectively _destroying_ the account. Compared with `close` which will simply return all the rent from an account.

Update the `close` account constraint logic
- sends all lamports to the `[target]`
- reallocates space on the account to 0
- assigns the account to the solana program
With this new logic, the `CLOSED_ACCOUNT_DISCRIMINATOR` is no longer needed as it's not possible to reinitialize the account in subsequent transaction simply by sending lamports to it.

Still TODO
- [x] A review from someone else that the new constraint logic is valid
- [x] Adding a program test to the `/misc` folder
- [x] Add documentation for the new `destroy` constraint, and if needed update the `close` account constraint

### CODE REVIEW

**Comment by Henry-E** [comment]
Tests passing, just needs a review @armaniferrante @callensm

**Comment by callensm** [comment]
`destroy` is a bit misleading to the purpose of the new constraint, maybe renaming it to something like `archive` would be more semantic?

**Comment by stegaBOB** [comment]
Since the account is being permanently killed (if I'm understanding this PR correctly), would something potentially even stronger like `permanently_destroy` or `destroy_forever` be better?

**Comment by Henry-E** [comment]
We had a bit of [bikeshedding discussion](https://discord.com/channels/889577356681945098/891724485177245717/1012734232029839520) already around the name. Anchor tends to have a preference for single word constraints. While I like the verbosity of `destroy_forever` I'm not sure what it would mean to `destroy_temporarily`. With `close`, the account can be `open`ed again or `init` in our case. There is no general concept of `undestroy`ing something.

**Comment by Henry-E** [comment]
Ok added a bunch of tests to verify the behaviour the of the new constraint.
- The `destroy` function won't work outside of the constraint usage as the function will fail to serialize the data as the account has been resized to only 8 bytes of space
- Add tests to verify that the account can't be reloaded or reinitialized after being `destroy`ed

Obviously if a smart contract dev really wants to, they can just write a custom function and pass in the destroyed account as an account info, then update all of the values on it manually to allow them to reuse the account or get back the 8 bytes of rent.

**Pull request closed without merging**
