### PR TITLE
feat: programs section in Anchor.toml

### PR DESCRIPTION
**Pull request by hrls**

### CODE REVIEW

**Comment by armaniferrante** [comment]
Can you explain the use case for this feature?

**Comment by hrls** [comment]
It allows specify hardcoded list of external program for CPI. As example we can mimic the same addresses on test validator as for testnet.

**Comment by armaniferrante** [comment]
I think this is redundant with the `[[test.genesis]]` feature https://github.com/project-serum/anchor/blob/master/examples/misc/Anchor.toml#L5.

Can you try that out and confirm?

**Comment by tomlinton** [comment]
Closing as stale.

**Pull request closed without merging**
