### PR TITLE
Remove depricated: literal constraints

### LINKED ISSUE #901: Remove deprecated account constraints
`belongs_to` and raw literal are deprecated from v0.11, should we rid them from the code?

- [x] `belongs_to` -- https://github.com/project-serum/anchor/pull/907
- [ ] raw literal -- https://github.com/project-serum/anchor/pull/927

### PR DESCRIPTION
**Pull request by NBNARADHYA**
Changes: 
1. Removes literal constraints support which was depricated.
2. Fixes #901

### CODE REVIEW

**Comment by NBNARADHYA** [comment]
@fanatid I have created a draft for this pr which fixes #901. Would you please approve workflow run for this ? So that I will be able to modify tests and add new ones if it fails. Thanks :)

**Comment by NBNARADHYA** [comment]
@fanatid  please approve workflow run!

**Comment by fanatid** [comment]
@NBNARADHYA please research how to run actions on your fork. You can start from editing these lines: https://github.com/project-serum/anchor/blob/master/.github/workflows/tests.yaml#L3-L9

**Comment by NBNARADHYA** [comment]
Oh. My bad! I thought github would atleast display actions in forked repo and I could run it manually but I wasn't able to. So, I assumed it was disabled on forked repo! Thanks @fanatid

**Comment by NBNARADHYA** [comment]
@fanatid I fixed the issues, and all tests are passing except CFO. Because it has a [submodule](https://github.com/project-serum/stake/blob/f04b2aaf8817dac4c8d89e75eaaa0c099dfbf166/programs/lockup/src/lib.rs#L270) which uses literal constraints.

I am not sure on how to tackle this ? Should I first get changes merged over there so that the tests pass over here ?

**Comment by armaniferrante** [comment]
> I am not sure on how to tackle this ? Should I first get changes merged over there so that the tests pass over here ?

Yes, please open a pr on the submodule.

**Comment by NBNARADHYA** [comment]
@fanatid I have made a pr to the stake repo: project-serum/stake#21

**Comment by NBNARADHYA** [comment]
The submodules which were linked to this repository were: 
https://github.com/project-serum/serum-dex,
https://github.com/project-serum/swap.git,
https://github.com/project-serum/stake.git,
https://github.com/armaniferrante/auction-house

All of these except [stake](https://github.com/project-serum/stake.git) are "literal constraint" free. So, I have made the changes to only stake repo @fanatid

**Comment by armaniferrante** [comment]
Closing as stale.

**Pull request closed without merging**
