### PR TITLE
spl: Added token-2022 extensions' wrappers

### PR DESCRIPTION
**Pull request by harsh4786**

### CODE REVIEW

**Comment by Henry-E** [comment]
While this does look good there are spaces in the directory names which is not ideal

**Comment by harsh4786** [comment]
Screenshot from 2022-11-19 21-15-46
You mean this space?

**Comment by Henry-E** [comment]
Space, like an empty character. It's usually bad to have them in a path. Better to use `-` or something else to append `extension`

**Comment by harsh4786** [comment]
Okay got it, so i make a new pr with the updated directory then it'd be good to go right?

**Comment by Henry-E** [comment]
It can be the same PR just a new commit to change the path of the files /
directories

**Comment by harsh4786** [comment]
how about now?

**Comment by Henry-E** [comment]
Looks good thanks. Will merge soon

**Comment by Henry-E** [comment]
Just noticed this PR doesn't 
- add any imports to the `cargo.toml` to allow the `use` of the token 2022 crate
- doesn't add a feature flag for using these features, similar to how serum dex requires a special feature flag
- doesn't have a `mod` file that exports the functions from the sub directory (at least I think that's what you'd need?)

This just the basic stuff that I've noticed might be missing and would prevent compiling / even accessing the new function, there might be more I didn't spot.

At the very least @harsh4786 you'd need to add a simple test to `misc` which imports the new token extension features and uses a least one of them. Then you should run into all of the above issues plus maybe more?

**Pull request closed without merging**
