### PR TITLE
ts: Fix IDL type issues

### PR DESCRIPTION
**Pull request by Juici**
### Changelog

- Fix the issue where nested user defined types are decoded to `never`.
- Fix the issue where enums are decoded incorrectly.
- Add type mapping to `Buffer` for the `bytes` type.

## Notes

Currently the changes made would result in enum variant names being as described in the IDL, that means that no case conversion would be done, this would be a breaking change. This could be mitigated by either storing the camelcased enum variant names in the IDL, or by doing the camelcase conversion at a type level.

In terms of camelcase at a type level, I have created a demo here: https://github.com/Juici/camelcase-ts.

### CODE REVIEW

**Comment by ElderJoy** [comment]
Hi Anchor team,
It is very useful feature. We want to use it in our project ASAP. Do you have plans about where you going to merge it?

**Comment by neery1218** [comment]
Hey! Also blocked by this. Are there any issues with merging?

**Comment by Boiethios** [comment]
Hey, any update? This PR fixes a serious problem because, right now, all nested structures are generated as `never`. If you need some contribution for merging it, please tell me.

**Comment by Juici** [comment]
Any feedback from the anchor team on what is blocking this would be greatly appreciated. Currently I have to rely on using the npm package [patch-package](https://www.npmjs.com/package/patch-package) to patch the `@project-serum/anchor` package to apply these fixes.

**Comment by Juici** [comment]
Superceded by: https://github.com/coral-xyz/anchor/pull/2482

**Pull request closed without merging**
