### PR TITLE
implemented DerefMut for TokenAccount

### PR DESCRIPTION
**Pull request by vkomenda**
I've implemented the missing instance of `DerefMut` for the `TokenAccount` newtype.

### CODE REVIEW

**Comment by armaniferrante** [comment]
Can you elaborate on the use case? Only the token program can mutate `TokenAccount` data, and so implementing `DerefMut` might be unnecessary, if I'm not missing something.

**Comment by vkomenda** [comment]
> Can you elaborate on the use case? Only the token program can mutate `TokenAccount` data, and so implementing `DerefMut` might be unnecessary, if I'm not missing something.

Sure, we need this to move NFT ownership to a PDA for escrow. That takes mutation of the owner field in the SPL `Account` struct.

**Comment by vkomenda** [comment]
@armaniferrante Are you suggesting to use the transfer instruction instead to change ownership?

**Comment by armaniferrante** [comment]
> @armaniferrante Are you suggesting to use the transfer instruction instead to change ownership?

Yes. Or `SetAuthority`. I suspect what you are trying to do won't work as expected.

**Pull request closed without merging**
