### PR TITLE
Stopped serializing enums that are not serializable

### PR DESCRIPTION
**Pull request by Buzzec**
Currently all enums are being added to the idl even ones that don't meet the requirements. This fixes it by adding the same checks as structs

### CODE REVIEW

**Comment by Henry-E** [comment]
This has the thumbs up from armani, which is some indication that it's needed / was missing. 

The code itself looks good. It checks that the enum has serializable on it and that's public. Seems reasonable. Not sure if this should be in the changelog?

**Comment by Henry-E** [comment]
@Buzzec would like to merge this but it needs a changelog added to it. It appears that `allow edits from maintainers` might not be activated on this PR?

`- lang: Stop serializing enums that are not serializable ([#2042](https://github.com/coral-xyz/anchor/pull/2042))` here's the line to add to the `fixes` section of the changelog anyway.

**Comment by Henry-E** [comment]
I will probably just repurpose this into a new PR and merge it because trying to include private enums in the IDL (which some people have been complaining about) seems like clearly incorrect behaviour.

**Comment by Henry-E** [comment]
Just reading through how the attributes checks are done. I'm assuming this is comprehensive to all the enum types that serializable in anchor but don't know for certain? It seems like if there are any missing enum types that should be being serialized we will find out very soon, although I'm not a fan of that approach.

I'm probably going to switch up the variable names as well to `isSerializable` since it's a bool and `serializable` by itself is minorly confusing.

**Comment by Henry-E** [comment]
Ugh, this really needs a test as well

**Comment by Buzzec** [comment]
Was fixed in #2310

**Pull request closed without merging**
